version: "3.9"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "1111"
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass 1111
    environment:
      - REDIS_PASSWORD=1111
    volumes:
      - cache:/data

volumes:
  db:
    driver: local
  cache:
    driver: local
